### ISSUE TITLE
Criar uma conta no meetup do PyLadies Natal

### ISSUE THREAD

**Issue by deboraazevedo** [PyLadiesNatal/organization#2]
Uma conta no meetup seria bom para aparecermos no site oficial do PyLadies (lá tem uma parte que mostra os próximos encontros) e também para organizar quem se inscreve e vai nos nossos encontros.

**Comment by deboraazevedo** [comment]
Acho que vou encerrar essa issue, pq o meetup é pago, 5 a 7 dólares por mês, e a gente usaria bem pouco.

**Comment by kessiacastro** [comment]
Concordo o/
